# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(db_column='comment_ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('portrait_url', models.CharField(blank=True, max_length=45, null=True)),
                ('is_admin', models.IntegerField(blank=True, null=True)),
                ('num_of_wiki', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(blank=True, max_length=45, null=True)),
                ('img_url', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Wiki',
            },
        ),
        migrations.CreateModel(
            name='WikiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Wiki_User',
            },
        ),
    ]
