-- MySQL Script generated by MySQL Workbench
-- 01/02/17 09:50:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`wiki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`wiki` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `introduction` TEXT NULL,
  `content` TEXT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `time` DATETIME NULL,
  `img_url` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `hits` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `account` VARCHAR(45) NOT NULL,
  `password` VARCHAR(250) NULL,
  `portrait_url` VARCHAR(45) NULL,
  `last_login` DATETIME NULL,
  `is_admin` TINYINT(1) NULL,
  `num_of_wiki` INT NULL DEFAULT 0,
  PRIMARY KEY (`account`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wiki_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`wiki_user` (
  `wiki_id` INT NOT NULL,
  `user_account` VARCHAR(45) NOT NULL,
  `relationship` INT NULL,
  INDEX `fk_Wiki_has_User_User1_idx` (`user_account` ASC),
  INDEX `fk_Wiki_has_User_Wiki_idx` (`wiki_id` ASC),
  PRIMARY KEY (`wiki_id`, `user_account`),
  CONSTRAINT `fk_Wiki_has_User_Wiki`
    FOREIGN KEY (`wiki_id`)
    REFERENCES `mydb`.`wiki` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Wiki_has_User_User1`
    FOREIGN KEY (`user_account`)
    REFERENCES `mydb`.`user` (`account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `time` DATETIME NULL,
  `wiki_title` VARCHAR(45) NULL,
  `user_account` VARCHAR(45) NULL,
  PRIMARY KEY (`comment_id`),

  CONSTRAINT `fk_comment_User1`
    FOREIGN KEY (`user_account`)
    REFERENCES `mydb`.`user` (`account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
