-- MySQL Script generated by MySQL Workbench
-- 01/01/17 20:02:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Wiki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Wiki` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `introduction` TEXT NULL,
  `content` TEXT NULL,
  `status` INT NULL,
  `time` DATETIME NULL,
  `img_url` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `account` VARCHAR(45) NOT NULL,
  `password` VARCHAR(250) NULL,
  `portrait_url` VARCHAR(45) NULL,
  `is_admin` INT NULL,
  `num_of_wiki` INT NULL DEFAULT 0,
  PRIMARY KEY (`account`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Wiki_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Wiki_User` (
  `Wiki_ID` INT NOT NULL,
  `User_account` VARCHAR(45) NOT NULL,
  `relationship` INT NULL,
  PRIMARY KEY (`Wiki_ID`, `User_account`),
  INDEX `fk_Wiki_has_User_User1_idx` (`User_account` ASC),
  INDEX `fk_Wiki_has_User_Wiki_idx` (`Wiki_ID` ASC),
  CONSTRAINT `fk_Wiki_has_User_Wiki`
    FOREIGN KEY (`Wiki_ID`)
    REFERENCES `mydb`.`Wiki` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Wiki_has_User_User1`
    FOREIGN KEY (`User_account`)
    REFERENCES `mydb`.`User` (`account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `comment_ID` INT NOT NULL,
  `content` TEXT NULL,
  `time` DATETIME NULL,
  `Wiki_ID` INT NOT NULL,
  `User_account` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`comment_ID`, `Wiki_ID`, `User_account`),
  INDEX `fk_comment_Wiki1_idx` (`Wiki_ID` ASC),
  INDEX `fk_comment_User1_idx` (`User_account` ASC),
  CONSTRAINT `fk_comment_Wiki1`
    FOREIGN KEY (`Wiki_ID`)
    REFERENCES `mydb`.`Wiki` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_User1`
    FOREIGN KEY (`User_account`)
    REFERENCES `mydb`.`User` (`account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
